"""
Dual-model reviewer: sends your prompt to Claude, Gemini, or ChatGPT first,
then passes the response to another model for review/validation.

Install:  pip install anthropic google-genai openai
Env vars: ANTHROPIC_API_KEY, GEMINI_API_KEY, OPENAI_API_KEY
"""

import os
import sys
import base64
import anthropic

sys.path.insert(0, r"C:\Python Scripts")
from api_usage_tracker import (log_from_anthropic_response,
                                log_from_gemini_response,
                                log_from_openai_response)
from google import genai
from google.genai import types as genai_types

FIRST_MAX_TOKENS = 16000
REVIEW_MAX_TOKENS = 32000

REVIEW_SYSTEM = (
    "You are a critical reviewer. The user will show you a response generated by "
    "another AI. Point out any errors, gaps, or improvements, then deliver a final "
    "refined answer. Be concise."
)

SYNTHESIS_SYSTEM = (
    "You are a final synthesis model. You will receive an original question, "
    "a first AI's answer, and a second AI's review of that answer. "
    "Weigh both perspectives critically, correct any errors, fill any gaps, "
    "and deliver the single best definitive answer."
)

# Pricing in USD per 1M tokens: (input, output)
PRICING = {
    "claude-opus-4-8":   (5.00, 25.00),
    "claude-sonnet-4-6": (3.00, 15.00),
    "claude-haiku-4-5":  (1.00,  5.00),
    "gemini-2.5-flash":  (0.30,  2.50),
    "gemini-2.5-pro":    (1.25, 10.00),
    "gemini-3.5-flash":  (0.30,  2.50),
    "gpt-4o":            (2.50, 10.00),
    "gpt-4o-mini":       (0.15,  0.60),
    "gpt-4.1":           (2.00,  8.00),
    "gpt-4.1-mini":      (0.40,  1.60),
}

def _cost(model: str, in_tok: int, out_tok: int) -> float:
    in_rate, out_rate = PRICING.get(model, (5.00, 25.00))
    return (in_tok * in_rate + out_tok * out_rate) / 1_000_000


def _history_to_gemini(history: list) -> list:
    """Convert [{role: user/assistant, content: str}] to Gemini Content objects."""
    result = []
    for msg in history:
        role = "model" if msg["role"] == "assistant" else "user"
        result.append(genai_types.Content(
            role=role,
            parts=[genai_types.Part(text=msg["content"])],
        ))
    return result


def _call_claude(prompt: str, system: str = "", max_tokens: int = FIRST_MAX_TOKENS,
                 model: str = "claude-opus-4-8",
                 image_bytes: bytes | None = None, image_mime: str = "image/jpeg",
                 pdf_bytes: bytes | None = None,
                 history: list | None = None, thinking: bool = True) -> dict:
    client = anthropic.Anthropic()
    if image_bytes or pdf_bytes:
        blocks = []
        if pdf_bytes:
            blocks.append({"type": "document", "source": {"type": "base64",
                           "media_type": "application/pdf",
                           "data": base64.standard_b64encode(pdf_bytes).decode()}})
        if image_bytes:
            blocks.append({"type": "image", "source": {"type": "base64", "media_type": image_mime,
                           "data": base64.standard_b64encode(image_bytes).decode()}})
        blocks.append({"type": "text", "text": prompt})
        current_content = blocks
    else:
        current_content = prompt
    messages = list(history or []) + [{"role": "user", "content": current_content}]
    kwargs = dict(
        model=model,
        max_tokens=max_tokens,
        messages=messages,
    )
    if thinking:
        kwargs["thinking"] = {"type": "adaptive"}
    if system:
        kwargs["system"] = system
    response = client.messages.create(**kwargs)
    text = next(b.text for b in response.content if b.type == "text")
    in_tok  = response.usage.input_tokens
    out_tok = response.usage.output_tokens
    log_from_anthropic_response(response, label="dual_model_reviewer")
    return {"text": text, "input_tokens": in_tok, "output_tokens": out_tok, "cost_usd": _cost(model, in_tok, out_tok)}


def _call_gemini(prompt: str, system: str = "", max_tokens: int = FIRST_MAX_TOKENS,
                 model: str = "gemini-2.5-flash",
                 image_bytes: bytes | None = None, image_mime: str = "image/jpeg",
                 pdf_bytes: bytes | None = None,
                 history: list | None = None) -> dict:
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    current_parts = []
    if pdf_bytes:
        current_parts.append(genai_types.Part.from_bytes(data=pdf_bytes, mime_type="application/pdf"))
    if image_bytes:
        current_parts.append(genai_types.Part.from_bytes(data=image_bytes, mime_type=image_mime))
    current_parts.append(genai_types.Part(text=prompt))
    contents = _history_to_gemini(history or []) + [
        genai_types.Content(role="user", parts=current_parts)
    ]
    response = client.models.generate_content(
        model=model,
        contents=contents,
        config=genai_types.GenerateContentConfig(
            system_instruction=system or None,
            max_output_tokens=max_tokens,
        ),
    )
    meta    = response.usage_metadata
    in_tok  = meta.prompt_token_count or 0
    out_tok = meta.candidates_token_count or 0
    log_from_gemini_response(response, model=model, label="dual_model_reviewer")
    return {"text": response.text, "input_tokens": in_tok, "output_tokens": out_tok, "cost_usd": _cost(model, in_tok, out_tok)}


def _call_openai(prompt: str, system: str = "", max_tokens: int = FIRST_MAX_TOKENS,
                 model: str = "gpt-4o",
                 image_bytes: bytes | None = None, image_mime: str = "image/jpeg",
                 pdf_bytes: bytes | None = None,
                 history: list | None = None) -> dict:
    from openai import OpenAI
    client = OpenAI()
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    for msg in (history or []):
        messages.append({"role": msg["role"], "content": msg["content"]})
    if image_bytes:
        b64 = base64.standard_b64encode(image_bytes).decode()
        user_content = [
            {"type": "image_url", "image_url": {"url": f"data:{image_mime};base64,{b64}"}},
            {"type": "text", "text": prompt},
        ]
    else:
        if pdf_bytes:
            prompt = "[PDF attached — not supported for OpenAI in this integration]\n\n" + prompt
        user_content = prompt
    messages.append({"role": "user", "content": user_content})
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        max_tokens=max_tokens,
    )
    text    = response.choices[0].message.content or ""
    in_tok  = response.usage.prompt_tokens
    out_tok = response.usage.completion_tokens
    log_from_openai_response(response, model=model, label="dual_model_reviewer")
    return {"text": text, "input_tokens": in_tok, "output_tokens": out_tok, "cost_usd": _cost(model, in_tok, out_tok)}


def _dispatch(provider: str, prompt: str, system: str = "", max_tokens: int = FIRST_MAX_TOKENS,
              model_id: str = "", image_bytes: bytes | None = None, image_mime: str = "image/jpeg",
              pdf_bytes: bytes | None = None,
              history: list | None = None, thinking: bool = True) -> dict:
    if provider == "claude":
        return _call_claude(prompt, system=system, max_tokens=max_tokens, model=model_id or "claude-opus-4-8",
                            image_bytes=image_bytes, image_mime=image_mime, pdf_bytes=pdf_bytes,
                            history=history, thinking=thinking)
    if provider == "openai":
        return _call_openai(prompt, system=system, max_tokens=max_tokens, model=model_id or "gpt-4o",
                            image_bytes=image_bytes, image_mime=image_mime, pdf_bytes=pdf_bytes,
                            history=history)
    return _call_gemini(prompt, system=system, max_tokens=max_tokens, model=model_id or "gemini-2.5-flash",
                        image_bytes=image_bytes, image_mime=image_mime, pdf_bytes=pdf_bytes,
                        history=history)


def run(user_prompt: str, first_model: str = "claude") -> dict:
    second_model = "gemini" if first_model == "claude" else "claude"

    print(f"\n[1/2] {first_model.upper()} answering your prompt…")
    r1 = _dispatch(first_model, user_prompt, max_tokens=FIRST_MAX_TOKENS)
    print(f"\n--- {first_model.upper()} response ---\n{r1['text']}\n")
    print(f"    tokens: {r1['input_tokens']} in / {r1['output_tokens']} out  (~${r1['cost_usd']:.4f})")

    review_prompt = (
        f"Original question summary: {user_prompt[:200]}\n\n"
        f"Response to review:\n{r1['text']}"
    )
    print(f"[2/2] {second_model.upper()} reviewing…")
    r2 = _dispatch(second_model, review_prompt, system=REVIEW_SYSTEM, max_tokens=REVIEW_MAX_TOKENS)
    print(f"\n--- {second_model.upper()} review + final answer ---\n{r2['text']}\n")
    print(f"    tokens: {r2['input_tokens']} in / {r2['output_tokens']} out  (~${r2['cost_usd']:.4f})")
    print(f"\nTotal estimated cost: ~${r1['cost_usd'] + r2['cost_usd']:.4f}")

    return {
        "first_model":      first_model,
        "second_model":     second_model,
        "initial_response": r1["text"],
        "final_response":   r2["text"],
        "call1_cost_usd":   r1["cost_usd"],
        "call2_cost_usd":   r2["cost_usd"],
    }


if __name__ == "__main__":
    prompt = input("Prompt: ").strip()
    if not prompt:
        raise SystemExit("No prompt entered.")

    raw = input("Start with [c]laude or [g]emini? (default: claude) ").strip().lower()
    first = "gemini" if raw.startswith("g") else "claude"

    run(prompt, first_model=first)
